export const translations = {
  en: {
    nav: { dashboard: "Dashboard", workout: "Titan Generator", nutrition: "Nutrition", coach: "Titan Coach", profile: "My Profile", settings: "Settings" },
    dashboard: { welcome: "Welcome back", level: "Current Level", workouts: "Workouts", minutes: "Minutes", streak: "Streak", calories: "Calories", generate: "Generate Today's Workout", recent: "Recent Activity", daysAgo: "days ago", session: "Titan Session" },
    workout: { title: "Titan Generator", subtitle: "Biometric-driven programming.", parameters: "Session Parameters", goal: "Primary Goal", split: "Weekly Split", focus: "Session Focus", experience: "Experience", frequency: "Frequency", duration: "Duration", equipment: "Equipment", generateBtn: "Generate Titan Plan", warmUp: "Warm Up", coolDown: "Cool Down", routine: "Routine", save: "Save", edit: "Edit Plan", close: "Close", fullWeek: "★ Full Week Program" },
    nutrition: { title: "Nutrition & Fuel", subtitle: "Calculated Requirements & AI Tracking.", calculator: "Nutrition Calculator", deficit: "Deficit (Cut)", maintenance: "Maintenance (TDEE)", surplus: "Surplus (Bulk)", logMeal: "Log Meal", calories: "Calories", protein: "Protein", carbs: "Carbs", fats: "Fats", add: "Add", noMeals: "No meals logged today." },
    coach: { title: "Titan Coach", subtitle: "Elite level guidance available 24/7.", placeholder: "Ask about your form, diet, or workout...", sending: "Sending..." },
    profile: { title: "Athlete Profile", subtitle: "Manage your biometrics.", personal: "Personal Details", fitness: "Fitness Profile", name: "Full Name", age: "Age", height: "Height", weight: "Weight", gender: "Gender", level: "Experience Level", genetics: "Genetic Notes", save: "Save Changes", saved: "Profile Saved", account: "Account Management", changePass: "Change Password", deleteAcc: "Delete Account" },
    settings: { title: "Settings", subtitle: "App preferences and information.", appearance: "Appearance", theme: "App Theme", themeDesc: "Toggle light/dark mode.", language: "Language", langDesc: "Select your preferred language.", about: "About Titan", data: "Data Management", reset: "Reset Application", logout: "Log Out" },
    auth: { title: "Titan AI", subtitle: "Your personal AI fitness architect.", google: "Continue with Google", apple: "Continue with Apple", facebook: "Continue with Facebook", email: "Or continue with email", guest: "Continue as Guest", login: "Log In / Sign Up", personalStep: "About You", fitnessStep: "Fitness Profile", back: "Back", complete: "Complete Setup" }
  },
  hu: {
    nav: { dashboard: "Irányítópult", workout: "Titan Generátor", nutrition: "Táplálkozás", coach: "Titan Edző", profile: "Profilom", settings: "Beállítások" },
    dashboard: { welcome: "Üdv újra", level: "Jelenlegi szint", workouts: "Edzések", minutes: "Perc", streak: "Széria", calories: "Kalória", generate: "Mai edzés generálása", recent: "Legutóbbi aktivitás", daysAgo: "napja", session: "Titan Edzés" },
    workout: { title: "Titan Generátor", subtitle: "Biometrikus alapú tervezés.", parameters: "Edzés paraméterek", goal: "Elsődleges cél", split: "Heti felosztás", focus: "Fókusz", experience: "Tapasztalat", frequency: "Gyakoriság", duration: "Időtartam", equipment: "Felszerelés", generateBtn: "Terv Generálása", warmUp: "Bemelegítés", coolDown: "Levezetés", routine: "Gyakorlatok", save: "Mentés", edit: "Szerkesztés", close: "Bezárás", fullWeek: "★ Teljes Heti Program" },
    nutrition: { title: "Táplálkozás", subtitle: "Számított igények és követés.", calculator: "Tápanyag Kalkulátor", deficit: "Deficit (Fogyás)", maintenance: "Szintentartás", surplus: "Többlet (Tömegnövelés)", logMeal: "Étkezés naplózása", calories: "Kalória", protein: "Fehérje", carbs: "Szénhidrát", fats: "Zsír", add: "Hozzáad", noMeals: "Nincs naplózott étkezés." },
    coach: { title: "Titan Edző", subtitle: "Profi tanácsadás 24/7.", placeholder: "Kérdezz a formáról, diétáról...", sending: "Küldés..." },
    profile: { title: "Sportoló Profil", subtitle: "Biometrikus adatok kezelése.", personal: "Személyes Adatok", fitness: "Fitnesz Profil", name: "Teljes Név", age: "Életkor", height: "Magasság", weight: "Súly", gender: "Nem", level: "Tapasztalati Szint", genetics: "Genetikai Jegyzetek", save: "Mentés", saved: "Mentve", account: "Fiók Kezelése", changePass: "Jelszó Csere", deleteAcc: "Fiók Törlése" },
    settings: { title: "Beállítások", subtitle: "Alkalmazás preferenciák.", appearance: "Megjelenés", theme: "Téma", themeDesc: "Világos/Sötét mód.", language: "Nyelv", langDesc: "Válasszon nyelvet.", about: "A Titan-ról", data: "Adatkezelés", reset: "Alaphelyzet", logout: "Kijelentkezés" },
    auth: { title: "Titan AI", subtitle: "Személyi AI fitnesz építész.", google: "Folytatás Google-lel", apple: "Folytatás Apple-lel", facebook: "Folytatás Facebook-kal", email: "Vagy folytatás e-maillel", guest: "Folytatás Vendégként", login: "Belépés / Regisztráció", personalStep: "Rólad", fitnessStep: "Fitnesz Profil", back: "Vissza", complete: "Kész" }
  },
  ar: {
    nav: { dashboard: "لوحة القيادة", workout: "مولد تيتان", nutrition: "التغذية", coach: "مدرب تيتان", profile: "ملفي الشخصي", settings: "الإعدادات" },
    dashboard: { welcome: "مرحبًا بعودتك", level: "المستوى الحالي", workouts: "التمارين", minutes: "دقائق", streak: "تتابع", calories: "سعرات", generate: "إنشاء تمرين اليوم", recent: "النشاط الأخير", daysAgo: "أيام مضت", session: "جلسة تيتان" },
    workout: { title: "مولد تيتان", subtitle: "برمجة تعتمد على القياسات الحيوية.", parameters: "معلمات الجلسة", goal: "الهدف الأساسي", split: "التقسيم الأسبوعي", focus: "التركيز", experience: "الخبرة", frequency: "التكرار", duration: "المدة", equipment: "المعدات", generateBtn: "إنشاء خطة تيتان", warmUp: "الإحماء", coolDown: "التهدئة", routine: "الروتين", save: "حفظ", edit: "تعديل", close: "إغلاق", fullWeek: "★ برنامج أسبوعي كامل" },
    nutrition: { title: "التغذية والوقود", subtitle: "المتطلبات المحسوبة وتتبع الذكاء الاصطناعي.", calculator: "حاسبة التغذية", deficit: "عجز (تنشيف)", maintenance: "صيانة (TDEE)", surplus: "فائض (تضخيم)", logMeal: "سجل وجبة", calories: "سعرات", protein: "بروتين", carbs: "كربوهيدرات", fats: "دهون", add: "إضافة", noMeals: "لا وجبات مسجلة اليوم." },
    coach: { title: "مدرب تيتان", subtitle: "توجيه بمستوى النخبة متاح 24/7.", placeholder: "اسأل عن النموذج أو النظام الغذائي...", sending: "جاري الإرسال..." },
    profile: { title: "ملف الرياضي", subtitle: "إدارة بياناتك الحيوية.", personal: "تفاصيل شخصية", fitness: "ملف اللياقة", name: "الاسم الكامل", age: "العمر", height: "الطول", weight: "الوزن", gender: "الجنس", level: "مستوى الخبرة", genetics: "ملاحظات وراثية", save: "حفظ التغييرات", saved: "تم الحفظ", account: "إدارة الحساب", changePass: "تغيير كلمة المرور", deleteAcc: "حذف الحساب" },
    settings: { title: "الإعدادات", subtitle: "تفضيلات التطبيق والمعلومات.", appearance: "المظهر", theme: "سمة التطبيق", themeDesc: "تبديل الوضع الفاتح/الداكن.", language: "اللغة", langDesc: "اختر لغتك المفضلة.", about: "حول تيتان", data: "إدارة البيانات", reset: "إعادة تعيين", logout: "تسجيل الخروج" },
    auth: { title: "تيتان AI", subtitle: "مهندس اللياقة البدنية الشخصي الخاص بك.", google: "المتابعة مع Google", apple: "المتابعة مع Apple", facebook: "المتابعة مع Facebook", email: "أو المتابعة بالبريد الإلكتروني", guest: "المتابعة كضيف", login: "دخول / تسجيل", personalStep: "عنك", fitnessStep: "ملف اللياقة", back: "رجوع", complete: "إكمال الإعداد" }
  },
  fr: {
    nav: { dashboard: "Tableau de bord", workout: "Générateur Titan", nutrition: "Nutrition", coach: "Coach Titan", profile: "Mon Profil", settings: "Paramètres" },
    dashboard: { welcome: "Bon retour", level: "Niveau actuel", workouts: "Séances", minutes: "Minutes", streak: "Série", calories: "Calories", generate: "Générer la séance", recent: "Activité récente", daysAgo: "jours", session: "Séance Titan" },
    workout: { title: "Générateur Titan", subtitle: "Programmation biométrique.", parameters: "Paramètres de séance", goal: "Objectif", split: "Répartition hebdo", focus: "Focus", experience: "Expérience", frequency: "Fréquence", duration: "Durée", equipment: "Équipement", generateBtn: "Générer Plan", warmUp: "Échauffement", coolDown: "Retour au calme", routine: "Routine", save: "Enregistrer", edit: "Modifier", close: "Fermer", fullWeek: "★ Programme Semaine Complète" },
    nutrition: { title: "Nutrition", subtitle: "Besoins calculés & suivi IA.", calculator: "Calculateur Nutrition", deficit: "Déficit (Sèche)", maintenance: "Maintien", surplus: "Surplus (Prise de masse)", logMeal: "Ajouter repas", calories: "Calories", protein: "Protéines", carbs: "Glucides", fats: "Lipides", add: "Ajouter", noMeals: "Aucun repas enregistré." },
    coach: { title: "Coach Titan", subtitle: "Conseils d'élite 24/7.", placeholder: "Posez une question...", sending: "Envoi..." },
    profile: { title: "Profil Athlète", subtitle: "Gérer vos données.", personal: "Détails Personnels", fitness: "Profil Fitness", name: "Nom Complet", age: "Âge", height: "Taille", weight: "Poids", gender: "Genre", level: "Niveau", genetics: "Notes Génétiques", save: "Enregistrer", saved: "Enregistré", account: "Gestion du Compte", changePass: "Changer Mot de Passe", deleteAcc: "Supprimer Compte" },
    settings: { title: "Paramètres", subtitle: "Préférences de l'application.", appearance: "Apparence", theme: "Thème", themeDesc: "Mode clair/sombre.", language: "Langue", langDesc: "Choisir la langue.", about: "À propos", data: "Données", reset: "Réinitialiser", logout: "Déconnexion" },
    auth: { title: "Titan AI", subtitle: "Votre architecte fitness personnel.", google: "Continuer avec Google", apple: "Continuer avec Apple", facebook: "Continuer avec Facebook", email: "Ou par email", guest: "Mode Invité", login: "Connexion / Inscription", personalStep: "À propos", fitnessStep: "Profil Fitness", back: "Retour", complete: "Terminer" }
  },
  es: {
    nav: { dashboard: "Tablero", workout: "Generador Titan", nutrition: "Nutrición", coach: "Entrenador Titan", profile: "Mi Perfil", settings: "Ajustes" },
    dashboard: { welcome: "Bienvenido", level: "Nivel actual", workouts: "Entrenamientos", minutes: "Minutos", streak: "Racha", calories: "Calorías", generate: "Generar Rutina", recent: "Actividad reciente", daysAgo: "días atrás", session: "Sesión Titan" },
    workout: { title: "Generador Titan", subtitle: "Programación biométrica.", parameters: "Parámetros", goal: "Objetivo", split: "División Semanal", focus: "Enfoque", experience: "Experiencia", frequency: "Frecuencia", duration: "Duración", equipment: "Equipo", generateBtn: "Generar Plan", warmUp: "Calentamiento", coolDown: "Enfriamiento", routine: "Rutina", save: "Guardar", edit: "Editar", close: "Cerrar", fullWeek: "★ Programa Semanal Completo" },
    nutrition: { title: "Nutrición", subtitle: "Requisitos y seguimiento IA.", calculator: "Calculadora", deficit: "Déficit (Definición)", maintenance: "Mantenimiento", surplus: "Superávit (Volumen)", logMeal: "Registrar Comida", calories: "Calorías", protein: "Proteínas", carbs: "Carbohidratos", fats: "Grasas", add: "Añadir", noMeals: "Sin comidas hoy." },
    coach: { title: "Entrenador Titan", subtitle: "Guía de élite 24/7.", placeholder: "Pregunta sobre dieta o forma...", sending: "Enviando..." },
    profile: { title: "Perfil Atleta", subtitle: "Gestiona tus datos.", personal: "Detalles Personales", fitness: "Perfil Fitness", name: "Nombre Completo", age: "Edad", height: "Altura", weight: "Peso", gender: "Género", level: "Nivel", genetics: "Notas Genéticas", save: "Guardar", saved: "Guardado", account: "Gestión de Cuenta", changePass: "Cambiar Contraseña", deleteAcc: "Borrar Cuenta" },
    settings: { title: "Ajustes", subtitle: "Preferencias de la app.", appearance: "Apariencia", theme: "Tema", themeDesc: "Modo claro/oscuro.", language: "Idioma", langDesc: "Seleccionar idioma.", about: "Sobre Titan", data: "Datos", reset: "Reiniciar", logout: "Cerrar Sesión" },
    auth: { title: "Titan AI", subtitle: "Tu arquitecto fitness personal.", google: "Seguir con Google", apple: "Seguir con Apple", facebook: "Seguir con Facebook", email: "O por correo", guest: "Modo Invitado", login: "Entrar / Registro", personalStep: "Sobre Ti", fitnessStep: "Perfil Fitness", back: "Atrás", complete: "Completar" }
  },
  ru: {
    nav: { dashboard: "Дашборд", workout: "Генератор Titan", nutrition: "Питание", coach: "Тренер Titan", profile: "Профиль", settings: "Настройки" },
    dashboard: { welcome: "С возвращением", level: "Текущий уровень", workouts: "Тренировки", minutes: "Минуты", streak: "Серия", calories: "Калории", generate: "Создать тренировку", recent: "Недавняя активность", daysAgo: "дн. назад", session: "Сессия Titan" },
    workout: { title: "Генератор Titan", subtitle: "Биометрическое программирование.", parameters: "Параметры", goal: "Цель", split: "Сплит", focus: "Фокус", experience: "Опыт", frequency: "Частота", duration: "Длительность", equipment: "Оборудование", generateBtn: "Создать план", warmUp: "Разминка", coolDown: "Заминка", routine: "Программа", save: "Сохранить", edit: "Изменить", close: "Закрыть", fullWeek: "★ Полная программа на неделю" },
    nutrition: { title: "Питание", subtitle: "Расчет и ИИ трекинг.", calculator: "Калькулятор", deficit: "Дефицит (Сушка)", maintenance: "Поддержание", surplus: "Профицит (Масса)", logMeal: "Записать еду", calories: "Ккал", protein: "Белки", carbs: "Углеводы", fats: "Жиры", add: "Добавить", noMeals: "Сегодня записей нет." },
    coach: { title: "Тренер Titan", subtitle: "Элитное руководство 24/7.", placeholder: "Спросите о форме или диете...", sending: "Отправка..." },
    profile: { title: "Профиль атлета", subtitle: "Управление данными.", personal: "Личные данные", fitness: "Фитнес профиль", name: "ФИО", age: "Возраст", height: "Рост", weight: "Вес", gender: "Пол", level: "Уровень", genetics: "Генетика", save: "Сохранить", saved: "Сохранено", account: "Управление аккаунтом", changePass: "Сменить пароль", deleteAcc: "Удалить аккаунт" },
    settings: { title: "Настройки", subtitle: "Предпочтения приложения.", appearance: "Внешний вид", theme: "Тема", themeDesc: "Светлая/Темная тема.", language: "Язык", langDesc: "Выберите язык.", about: "О Titan", data: "Данные", reset: "Сброс", logout: "Выйти" },
    auth: { title: "Titan AI", subtitle: "Ваш персональный фитнес-архитектор.", google: "Войти через Google", apple: "Войти через Apple", facebook: "Войти через Facebook", email: "Или через email", guest: "Войти как гость", login: "Вход / Регистрация", personalStep: "О вас", fitnessStep: "Фитнес профиль", back: "Назад", complete: "Завершить" }
  }
};